version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/movies_db
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:13  # Используем PostgreSQL 13
    container_name: movies_db_container  # Имя контейнера (удобно для логов)
    #restart: always  # Перезапуск при сбоях
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies_db
    ports:
      - "5432:5432"  # Маппинг порта контейнера на порт хоста
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
